# Generated by Django 4.2.3 on 2023-07-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Team Member Name', max_length=100)),
                ('contact_no', models.CharField(default=0, max_length=20)),
                ('alt_contact_no', models.CharField(default=0, max_length=20)),
                ('eMail', models.EmailField(default='your@email.com', max_length=254)),
                ('designation', models.CharField(default='Team Designation', max_length=100)),
                ('role_description', models.TextField(default='Describe the Designation')),
                ('image', models.ImageField(upload_to='media/images/')),
                ('website', models.CharField(blank=True, default='www.website.com', max_length=150, null=True)),
                ('twitter', models.CharField(blank=True, default='twitter.com/user', max_length=150, null=True)),
                ('facebook', models.CharField(blank=True, default='facebook.com/username', max_length=100, null=True)),
                ('linkdin', models.CharField(blank=True, default='linkdin.com/username', max_length=150, null=True)),
                ('instagram', models.CharField(blank=True, default='inatagram.com/username', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Our_Team_Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.TextField(default='Put Our Heading Over Here')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
