# Generated by Django 4.2.3 on 2024-01-01 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_header_for_recent_blog', models.TextField(blank=True, default='Header for Recent Blog Section', help_text='***** This Section Details Will Display on Recent Blog Section *****', null=True)),
                ('Blog_header_for_blog_page', models.TextField(blank=True, default='Header for Blog Page Section', help_text='***** This Section Details Will Display on Blog Section *****', null=True)),
                ('Blog_Display_Status', models.BooleanField(default=False, help_text='***** Check This box If you wanna Display this on your Web *****')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Header_and_Info_dumy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.TextField(blank=True, default=None, help_text='Put Contact Header Here', null=True)),
                ('location', models.CharField(blank=True, default=None, help_text='Put Location Here', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, default=None, help_text='Enter Your email as "your@email.com"', max_length=254, null=True)),
                ('contact', models.CharField(blank=True, default=None, help_text='Enter your Contact No.', max_length=100, null=True)),
                ('opening_hour', models.CharField(blank=True, default=None, help_text='Ex. Mon-Sat 10.00 AM - 09:00 PM', max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(default='Your Name', max_length=100)),
                ('contact_email', models.EmailField(default='your@email.com', max_length=254)),
                ('contact_subject', models.CharField(default='Subject', max_length=100)),
                ('contact_message', models.TextField(default='Your Message')),
                ('contact_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faq_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.TextField(blank=True, default='Put FAQ Header Here', null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faq_Sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FAQ_Question', models.CharField(blank=True, default='Put FAQ Question over here', max_length=150, null=True)),
                ('FAQ_Answer', models.TextField(blank=True, default='Put FAQ Answer over here', null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Our_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default='Client Name', max_length=200, null=True)),
                ('client_contact', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('client_alt_contact', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('client_type', models.CharField(blank=True, choices=[('Organization', 'Organization'), ('Person', 'Person'), (None, None)], default=None, max_length=50, null=True)),
                ('owner_name', models.CharField(blank=True, default='Owner Name', help_text='**Fill up these Entryes only if the client is an Organization', max_length=100, null=True)),
                ('owner_address', models.CharField(blank=True, default='Owner Address', help_text='**Fill up these Entryes only if the client is an Organization', max_length=100, null=True)),
                ('owner_contact', models.CharField(blank=True, default=0, help_text='**Fill up these Entryes only if the client is an Organization', max_length=20, null=True)),
                ('owner_alt_contact', models.CharField(blank=True, default=0, help_text='**Fill up these Entryes only if the client is an Organization', max_length=20, null=True)),
                ('owner_email', models.EmailField(blank=True, default='owner@email.com', help_text='**Fill up these Entryes only if the client is an Organization', max_length=100, null=True)),
                ('client_email', models.EmailField(blank=True, default='client@email.com', max_length=100, null=True)),
                ('client_address', models.CharField(blank=True, default='Client Address', max_length=100, null=True)),
                ('client_image', models.ImageField(blank=True, default='**You can only add one Image', null=True, upload_to='media/images/')),
                ('priority_status', models.BooleanField(default=False, help_text='**Check this box if you concider this Client Priority is High')),
            ],
        ),
        migrations.CreateModel(
            name='Our_Client_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.TextField(default='Put Your Client Header Here')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Our_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, default='Service Name', max_length=200, null=True)),
                ('service_description_summary', models.TextField(blank=True, default='Service Description', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Our_service_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.TextField(blank=True, default='Put Service Header Here', null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Our_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Team Member Name', max_length=100)),
                ('contact_no', models.CharField(default=0, max_length=20)),
                ('alt_contact_no', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('eMail', models.EmailField(default='your@email.com', max_length=254)),
                ('designation', models.CharField(default='Team Designation', max_length=100)),
                ('role_description', models.TextField(default='Describe the Designation')),
                ('image', models.ImageField(upload_to='media/images/')),
                ('address', models.TextField(blank=True, default='Members Address', null=True)),
                ('website', models.CharField(blank=True, default='www.website.com', max_length=150, null=True)),
                ('twitter', models.CharField(blank=True, default='twitter.com/user', max_length=150, null=True)),
                ('facebook', models.CharField(blank=True, default='facebook.com/username', max_length=100, null=True)),
                ('linkdin', models.CharField(blank=True, default='linkdin.com/username', max_length=150, null=True)),
                ('instagram', models.CharField(blank=True, default='inatagram.com/username', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Our_Team_Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.TextField(default='Put Our Heading Over Here')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Portfolio_name', models.CharField(blank=True, default='Portfolio Name', max_length=100, null=True)),
                ('Portfolio_type', models.CharField(blank=True, choices=[('Web_Development', 'Web_Development'), ('Desktop_Applications', 'Desktop_Applications'), ('Mobile_Applications', 'Mobile_Applications'), ('Next_JS_SEO', 'Next_JS_SEO'), (None, None)], default=None, max_length=100, null=True)),
                ('Portfolio_summary', models.CharField(blank=True, default='Portfolio Summary', max_length=300, null=True)),
                ('Portfolio_Description', models.TextField(blank=True, default='Portfolio Description', null=True)),
                ('portfolio_slug', models.SlugField(blank=True, default='portfolio_slug', help_text='**Slug has to be Unique for each Portfolio', max_length=100, null=True)),
                ('portfolio_image_1', models.ImageField(blank=True, help_text='**You can only add one Picture', null=True, upload_to='media/images/')),
                ('portfolio_image_alt_1', models.CharField(blank=True, default='Image Alt', help_text='**Add ALT Tag line over here', max_length=150, null=True)),
                ('portfolio_image_2', models.ImageField(blank=True, help_text='**You can only add one Picture', null=True, upload_to='media/images/')),
                ('portfolio_image_alt_2', models.CharField(blank=True, default='Image Alt', help_text='**Add ALT Tag line over here', max_length=150, null=True)),
                ('portfolio_image_3', models.ImageField(blank=True, help_text='**You can only add one Picture', null=True, upload_to='media/images/')),
                ('portfolio_image_alt_3', models.CharField(blank=True, default='Image Alt', help_text='**Add ALT Tag line over here', max_length=150, null=True)),
                ('portfolio_image_4', models.ImageField(blank=True, help_text='**You can only add one Picture', null=True, upload_to='media/images/')),
                ('portfolio_image_alt_4', models.CharField(blank=True, default='Image Alt', help_text='**Add ALT Tag line over here', max_length=150, null=True)),
                ('portfolio_publish_date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='**Set Published Date Here', null=True)),
                ('portfolio_site', models.CharField(blank=True, default='Put Site name to display', max_length=30, null=True)),
                ('portfolio_url', models.CharField(blank=True, default='Portfolio Url', help_text='**Put Portfolio URL here if Exists', max_length=100, null=True)),
                ('Portfolio_Display_Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=200)),
                ('contact', models.CharField(default=0, max_length=20)),
                ('designation', models.CharField(default='Reviewer Designation', max_length=50)),
                ('review', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Normal', 'Normal'), ('Bad', 'Bad'), ('Worst', 'Worst'), (None, None)], default=None, max_length=50)),
                ('testimonials', models.TextField(default='The Testimonials')),
                ('image', models.ImageField(blank=True, help_text='***You can only add one Picture', upload_to='media/images/')),
                ('status', models.BooleanField(default=False, help_text='***Check the Button to make it display on Your Site')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.TextField(default='Put Testimonials Header Here')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Title', models.CharField(blank=True, default='Blog Title', help_text='***** Add Blog Title Over Here *****', max_length=100, null=True, unique=True)),
                ('Blog_Summary', models.TextField(blank=True, default='Blog Summary', help_text='***** Add Blog Summary Over Here ***** ', null=True)),
                ('Blog_Image', models.ImageField(blank=True, help_text='***** Set Blog Image Over Here *****', null=True, upload_to='media/images/')),
                ('Blog_ALT_TAG', models.CharField(blank=True, default='Blog ALT TAG', help_text='***** Put ALT TAG for SEO perpouses *****', max_length=100, null=True)),
                ('Blog_Slug', models.CharField(blank=True, default='Blog-Slug', help_text='***** Put Blog Title and Replace it by ( - ) is Recomended *****', max_length=100, null=True, unique=True)),
                ('Author_Image', models.ImageField(blank=True, help_text='***** Update Auther Image Over Here *****', null=True, upload_to='media/images/')),
                ('Blog_Post_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Introduction_Paragraph_1', models.TextField(blank=True, default='Add Introduction Paragraph 1', help_text='***** Include Introduction Paragraph No. 1 *****', null=True)),
                ('Introduction_Paragraph_2', models.TextField(blank=True, default='Add Introduction Paragraph 2', help_text='***** Include Introduction Paragraph No. 2 *****', null=True)),
                ('Introduction_Paragraph_3', models.TextField(blank=True, default='Add Introduction Paragraph 3', help_text='***** Include Introduction Paragraph No. 3 *****', null=True)),
                ('Some_Quotation', models.CharField(blank=True, default='Add Quotation', help_text='***** Include Your Quotation *****', max_length=150, null=True)),
                ('Paragraph_1', models.TextField(blank=True, default='Add Paragraph 1', help_text='***** Include Paragraph No. 1 *****', null=True)),
                ('Paragraph_2', models.TextField(blank=True, default='Add Paragraph 2', help_text='***** Include Paragraph No. 2 *****', null=True)),
                ('Paragraph_3', models.TextField(blank=True, default='Add Paragraph 3', help_text='***** Include Paragraph No. 3 *****', null=True)),
                ('Headline_1', models.CharField(blank=True, default='Add Your HeadLine 1', help_text='***** Include HeadLine 1 *****', max_length=200, null=True)),
                ('Headline_1_Paragraph_1', models.TextField(blank=True, default='Add HeadLine 1 Paragraph 1', help_text='***** Include HeadLine 1 Paragraph No. 1 *****', null=True)),
                ('Headline_1_Paragraph_2', models.TextField(blank=True, default='Add HeadLine 1 Paragraph 2', help_text='***** Include HeadLine 1 Paragraph No. 2 *****', null=True)),
                ('Headline_1_Paragraph_3', models.TextField(blank=True, default='Add HeadLine 1 Paragraph 3', help_text='***** Include HeadLine 1 Paragraph No. 3 *****', null=True)),
                ('Image_for_HeadLine_1', models.ImageField(blank=True, help_text='***** Include Image for HeadLine 1 *****', null=True, upload_to='media/images/')),
                ('Image_for_HeadLine_1_ALT_TAG', models.CharField(blank=True, default='Add Image ALT TAG', help_text='***** Include ALT TAG for that Image *****', max_length=100, null=True)),
                ('Headline_2', models.CharField(blank=True, default='Add Your HeadLine 2', help_text='***** Include HeadLine 2 *****', max_length=200, null=True)),
                ('Headline_2_Paragraph_1', models.TextField(blank=True, default='Add HeadLine 2 Paragraph 1', help_text='***** Include HeadLine 2 Paragraph No. 1 *****', null=True)),
                ('Headline_2_Paragraph_2', models.TextField(blank=True, default='Add HeadLine 2 Paragraph 2', help_text='***** Include HeadLine 2 Paragraph No. 2 *****', null=True)),
                ('Headline_2_Paragraph_3', models.TextField(blank=True, default='Add HeadLine 2 Paragraph 3', help_text='***** Include HeadLine 2 Paragraph No. 3 *****', null=True)),
                ('Image_for_HeadLine_2', models.ImageField(blank=True, help_text='***** Include Image for HeadLine 2 *****', null=True, upload_to='media/images/')),
                ('Image_for_HeadLine_2_ALT_TAG', models.CharField(blank=True, default='Add Image ALT TAG', help_text='***** Include ALT TAG for that Image *****', max_length=100, null=True)),
                ('Headline_3', models.CharField(blank=True, default='Add Your HeadLine 3', help_text='***** Include HeadLine 3 *****', max_length=200, null=True)),
                ('Headline_3_Paragraph_1', models.TextField(blank=True, default='Add HeadLine 3 Paragraph 1', help_text='***** Include HeadLine 3 Paragraph No. 1 *****', null=True)),
                ('Headline_3_Paragraph_2', models.TextField(blank=True, default='Add HeadLine 3 Paragraph 2', help_text='***** Include HeadLine 3 Paragraph No. 2 *****', null=True)),
                ('Headline_3_Paragraph_3', models.TextField(blank=True, default='Add HeadLine 3 Paragraph 3', help_text='***** Include HeadLine 3 Paragraph No. 3 *****', null=True)),
                ('Image_for_HeadLine_3', models.ImageField(blank=True, help_text='***** Include Image for HeadLine 3 *****', null=True, upload_to='media/images/')),
                ('Image_for_HeadLine_3_ALT_TAG', models.CharField(blank=True, default='Add Image ALT TAG', help_text='***** Include ALT TAG for that Image *****', max_length=100, null=True)),
                ('Blog_Display_Status', models.BooleanField(default=False, help_text='***** Check This box If you wanna Display this on your Web')),
                ('Blog_Author_Name', models.ForeignKey(blank=True, help_text='***** Add Auther User Name *****', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
