# Generated by Django 4.2.3 on 2024-01-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Header_and_Info_dumy',
            new_name='Contact_Header_and_Info',
        ),
    ]
