# Generated by Django 4.2.3 on 2023-07-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0002_alter_our_team_alt_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Header_and_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.TextField(blank=True, default='Put Contact Header Here', null=True)),
                ('location', models.CharField(blank=True, default='Put Location Here', max_length=20, null=True)),
                ('contact', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('opening_hour', models.CharField(blank=True, default='Ex. Mon-Sat 10.00 AM - 09:00 PM', max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
