# Generated by Django 4.2.3 on 2024-01-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0003_rename_testimonials_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_header_and_info',
            name='contact',
            field=models.CharField(blank=True, choices=[('1234567890', '1234567890'), ('0987654321', '0987654321')], default=None, help_text='Enter your Contact No.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact_header_and_info',
            name='email',
            field=models.EmailField(blank=True, choices=[('apparky@protonmail.com', 'apparky@protonmain.com'), ('appariun.connect@gmail.com', 'appariun.connect@gmail.com')], default=None, help_text='Enter Your email as "your@email.com"', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact_header_and_info',
            name='location',
            field=models.CharField(blank=True, choices=[('Kolkata 28', 'Kolkata 28'), ('Berhampore, Murshidabad', 'Berhampore, Murshidabad')], default=None, help_text='Put Location Here', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact_header_and_info',
            name='opening_hour',
            field=models.CharField(blank=True, choices=[('Mon-Sat 10.00 AM - 09:00 PM', 'Mon-Sat 10.00 AM - 09:00 PM'), ('Sun-Sat 8.00 AM - 11:00 PM', 'Sun-Sat 8.00 AM - 11:00 PM')], default=None, help_text='Ex. Mon-Sat 10.00 AM - 09:00 PM', max_length=200, null=True),
        ),
    ]
