# Generated by Django 4.2.3 on 2023-07-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0003_contact_header_and_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_header_and_info',
            name='email',
            field=models.EmailField(blank=True, default='your@email.com', max_length=254, null=True),
        ),
    ]
