# Generated by Django 4.2.3 on 2023-07-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0004_contact_header_and_info_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_header_and_info',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
