# Generated by Django 4.2.3 on 2024-01-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0004_alter_contact_header_and_info_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='Author_Image',
            field=models.ImageField(help_text='***** Update Auther Image Over Here *****', null=True, upload_to='media/images/'),
        ),
    ]
