# Generated by Django 4.2.3 on 2024-01-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0005_alter_blog_content_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='Blog_Image',
            field=models.ImageField(help_text='***** Set Blog Image Over Here *****', null=True, upload_to='media/images/'),
        ),
    ]
