# Generated by Django 4.2.3 on 2023-07-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0005_alter_contact_header_and_info_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.TextField(blank=True, default='Put FAQ Header Here', null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
