# Generated by Django 4.2.3 on 2023-07-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0006_faq_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FAQ_Question', models.CharField(blank=True, default='Put FAQ Question over here', max_length=150, null=True)),
                ('FAQ_Answer', models.TextField(blank=True, default='Put FAQ Answer over here', null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
