# Generated by Django 4.2.3 on 2024-01-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0006_alter_blog_content_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_content',
            name='Blog_post_category',
            field=models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Entertainment', 'Entertainment'), ('Finance', 'Finance')], help_text='***** Add Post Category Here *****', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='Author_Image',
            field=models.ImageField(blank=True, help_text='***** Update Auther Image Over Here *****', null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='Blog_Image',
            field=models.ImageField(blank=True, help_text='***** Set Blog Image Over Here *****', null=True, upload_to='media/images/'),
        ),
    ]
