# Generated by Django 4.2.3 on 2023-07-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0007_faqs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQs',
            new_name='FAQ_Sets',
        ),
    ]
