# Generated by Django 4.2.3 on 2024-01-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0007_blog_content_blog_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='Blog_post_category',
            field=models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Entertainment', 'Entertainment'), ('Finance', 'Finance'), ('Others', 'Others')], help_text='***** Add Post Category Here *****', max_length=100),
        ),
    ]
