# Generated by Django 4.2.3 on 2023-07-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0008_rename_faqs_faq_sets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ_Header',
            new_name='F_A_Q_Header',
        ),
        migrations.RenameModel(
            old_name='FAQ_Sets',
            new_name='F_A_Q_Sets',
        ),
    ]
