# Generated by Django 4.2.3 on 2023-07-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0009_rename_faq_header_f_a_q_header_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='F_A_Q_Header',
            new_name='Faq_Header',
        ),
        migrations.RenameModel(
            old_name='F_A_Q_Sets',
            new_name='Faq_Sets',
        ),
    ]
