# Generated by Django 4.2.3 on 2023-07-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0010_rename_f_a_q_header_faq_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_service_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.TextField(blank=True, default='Put Service Header Here', null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
