# Generated by Django 4.2.3 on 2023-07-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0011_our_service_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, default='Service Name', max_length=200, null=True)),
                ('service_description', models.TextField(blank=True, default='Service Description', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
            ],
        ),
    ]
