# Generated by Django 4.2.3 on 2023-07-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0012_our_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_service',
            old_name='service_description',
            new_name='service_description_summary',
        ),
    ]
