# Generated by Django 4.2.3 on 2023-07-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0013_rename_service_description_our_service_service_description_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=200)),
                ('contact', models.CharField(default=0, max_length=20)),
                ('designation', models.CharField(default='Reviewer Designation', max_length=50)),
                ('review', models.CharField(default=None, max_length=50)),
                ('testimonials', models.TextField(default='The Testimonials')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.TextField(default='Put Testimonials Header Here')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
