# Generated by Django 4.2.3 on 2023-07-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0015_alter_testimonials_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='review',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Normal', 'Normal'), ('Bad', 'Bad'), ('Worst', 'Worst'), (None, None)], default=None, max_length=50),
        ),
    ]
