# Generated by Django 4.2.3 on 2023-07-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0016_alter_testimonials_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
    ]
