# Generated by Django 4.2.3 on 2023-07-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0017_testimonials_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=100)),
                ('email', models.EmailField(default='your@email.com', max_length=254)),
                ('subject', models.CharField(default='Subject', max_length=100)),
                ('message', models.TextField(default='Your Message')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
