# Generated by Django 4.2.3 on 2023-07-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0018_contact_us_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Client_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.TextField(default='Put Your Client Header Here')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
