# Generated by Django 4.2.3 on 2023-07-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0019_our_client_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='Client Name', max_length=200, null=True)),
                ('client_contact', models.CharField(default=0, max_length=20, null=True)),
                ('client_alt_contact', models.CharField(default=0, max_length=20, null=True)),
                ('client_type', models.CharField(choices=[('Organization', 'Organization'), ('Person', 'Person')], default=None, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, help_text='You can only add one Picture', upload_to='media/images/'),
        ),
    ]
