# Generated by Django 4.2.3 on 2023-07-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0020_our_client_alter_testimonials_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, help_text='***You can only add one Picture', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='status',
            field=models.BooleanField(default=False, help_text='Check the Button to make it display on Your Site'),
        ),
    ]
