# Generated by Django 4.2.3 on 2023-07-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0022_alter_testimonials_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_client',
            name='client_email',
            field=models.EmailField(default='client@email.com', max_length=100, null=True),
        ),
    ]
