# Generated by Django 4.2.3 on 2023-07-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0024_our_client_client_address_our_client_owner_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_client',
            name='owner_address',
            field=models.CharField(blank=True, default='Owner Address', help_text='**Fill up these Entryes only if the client is an Organization', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='our_client',
            name='owner_alt_contact',
            field=models.CharField(blank=True, default=0, help_text='**Fill up these Entryes only if the client is an Organization', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='our_client',
            name='owner_contact',
            field=models.CharField(blank=True, default=0, help_text='**Fill up these Entryes only if the client is an Organization', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='our_client',
            name='owner_email',
            field=models.EmailField(blank=True, default='owner@email.com', help_text='**Fill up these Entryes only if the client is an Organization', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='our_client',
            name='owner_name',
            field=models.CharField(blank=True, default='Owner Name', help_text='**Fill up these Entryes only if the client is an Organization', max_length=100, null=True),
        ),
    ]
