# Generated by Django 4.2.3 on 2023-07-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0025_alter_our_client_owner_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_client',
            name='client_status',
            field=models.BooleanField(default=False, help_text='**Check this box if the Client id High Confidence'),
        ),
    ]
