# Generated by Django 4.2.3 on 2023-07-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0026_our_client_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_client',
            name='client_image',
            field=models.ImageField(default='**You can only add one Image', upload_to='media/images/'),
        ),
    ]
