# Generated by Django 4.2.3 on 2023-07-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0028_alter_our_client_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_client',
            name='client_type',
            field=models.CharField(blank=True, choices=[('Organization', 'Organization'), ('Person', 'Person'), (None, None)], default=None, max_length=50, null=True),
        ),
    ]
