# Generated by Django 4.2.3 on 2023-07-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0029_alter_our_client_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_client',
            name='client_status',
            field=models.BooleanField(default=False, help_text='**Check this box if you concider this Client Priority is High'),
        ),
    ]
