# Generated by Django 4.2.3 on 2023-07-25 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0030_alter_our_client_client_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_client',
            old_name='client_status',
            new_name='priority_status',
        ),
    ]
