# Generated by Django 4.2.3 on 2023-07-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0032_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_team',
            name='address',
            field=models.TextField(blank=True, default='Members Address', null=True),
        ),
    ]
