# Generated by Django 4.2.3 on 2023-07-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0033_our_team_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image_alt',
            field=models.CharField(blank=True, default='Image Alt', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_slug',
            field=models.SlugField(blank=True, default='portfolio_slug', help_text='**Slug has to be Unique for each Portfolio', max_length=100, null=True),
        ),
    ]
