# Generated by Django 4.2.3 on 2023-07-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0034_portfolio_portfolio_image_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image_alt',
            field=models.CharField(blank=True, default='Image Alt', help_text='**Add ALT Tag line over here', max_length=150, null=True),
        ),
    ]
