# Generated by Django 4.2.3 on 2023-07-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0035_alter_portfolio_portfolio_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='Portfolio_type',
            field=models.CharField(blank=True, choices=[('Web_Development', 'Web_Development'), ('Desktop_Applications', 'Desktop_Applications'), ('Mobile_Applications', 'Mobile_Applications'), ('Next_JS_SEO', 'Next_JS_SEO'), (None, None)], default=None, max_length=100, null=True),
        ),
    ]
