# Generated by Django 4.2.3 on 2023-07-27 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0036_alter_portfolio_portfolio_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_publish_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_url',
            field=models.CharField(blank=True, default='Portfolio Url', help_text='**Put Portfolio URL here if Exists', max_length=100, null=True),
        ),
    ]
