# Generated by Django 4.2.3 on 2023-07-27 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0037_portfolio_portfolio_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_publish_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='**Set Published Date Here', null=True),
        ),
    ]
