# Generated by Django 4.2.3 on 2023-07-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0039_portfolio_portfolio_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_site',
            field=models.CharField(blank=True, default='Put Site name to display', max_length=30, null=True),
        ),
    ]
