# Generated by Django 4.2.3 on 2023-07-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0040_alter_portfolio_portfolio_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='portfolio_image',
            new_name='portfolio_image_1',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='portfolio_image_alt',
            new_name='portfolio_image_alt_1',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image_2',
            field=models.ImageField(blank=True, help_text='**You can only add one Picture', null=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image_3',
            field=models.ImageField(blank=True, help_text='**You can only add one Picture', null=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image_4',
            field=models.ImageField(blank=True, help_text='**You can only add one Picture', null=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image_alt_2',
            field=models.CharField(blank=True, default='Image Alt', help_text='**Add ALT Tag line over here', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image_alt_3',
            field=models.CharField(blank=True, default='Image Alt', help_text='**Add ALT Tag line over here', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image_alt_4',
            field=models.CharField(blank=True, default='Image Alt', help_text='**Add ALT Tag line over here', max_length=150, null=True),
        ),
    ]
