# Generated by Django 4.2.3 on 2023-07-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0042_alter_portfolio_portfolio_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image_1',
            field=models.ImageField(blank=True, help_text='**You can only add one Picture', null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image_alt_1',
            field=models.CharField(blank=True, default='Image Alt', help_text='**Add ALT Tag line over here', max_length=150, null=True),
        ),
    ]
