# Generated by Django 4.2.3 on 2023-08-01 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0043_alter_portfolio_portfolio_image_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us_form',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='contact_us_form',
            old_name='message',
            new_name='contact_message',
        ),
        migrations.RenameField(
            model_name='contact_us_form',
            old_name='name',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='contact_us_form',
            old_name='status',
            new_name='contact_status',
        ),
        migrations.RenameField(
            model_name='contact_us_form',
            old_name='subject',
            new_name='contact_subject',
        ),
    ]
