# Generated by Django 4.2.3 on 2023-08-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0044_rename_email_contact_us_form_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_header_for_recent_blog', models.CharField(blank=True, default='Header for Recent Blog Section', help_text='***** This Section Details Will Display on Recent Blog Section ', max_length=300, null=True)),
                ('Blog_header_for_blog_page', models.CharField(blank=True, default='Header for Blog Page Section', help_text='***** This Section Details Will Display on Blog Section', max_length=300, null=True)),
                ('Blog_Display_Status', models.BooleanField(default=False)),
            ],
        ),
    ]
