# Generated by Django 4.2.3 on 2023-11-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0046_alter_blog_header_blog_display_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_header',
            name='Blog_Display_Status',
            field=models.BooleanField(default=False, help_text='***** Check This box If you wanna Display this on your Web *****'),
        ),
        migrations.AlterField(
            model_name='blog_header',
            name='Blog_header_for_blog_page',
            field=models.TextField(blank=True, default='Header for Blog Page Section', help_text='***** This Section Details Will Display on Blog Section *****', null=True),
        ),
        migrations.AlterField(
            model_name='blog_header',
            name='Blog_header_for_recent_blog',
            field=models.TextField(blank=True, default='Header for Recent Blog Section', help_text='***** This Section Details Will Display on Recent Blog Section *****', null=True),
        ),
    ]
