# Generated by Django 4.2.3 on 2023-11-05 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myService', '0047_alter_blog_header_blog_display_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Title', models.CharField(blank=True, default='Blog Title', help_text='***** Add Blog Title Over Here *****', max_length=100, null=True)),
                ('Blog_Summary', models.TextField(blank=True, default='Blog Summary', help_text='***** Add Blog Summary Over Here ***** ', null=True)),
                ('Blog_Image', models.ImageField(blank=True, help_text='***** Set Blog Image Over Here *****', null=True, upload_to='media/images/')),
                ('Blog_Display_Status', models.BooleanField(default=False, help_text='***** Check This box If you wanna Display this on your Web')),
                ('Blog_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
