# Generated by Django 4.2.3 on 2023-11-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0048_blog_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_Content',
        ),
    ]
