# Generated by Django 4.2.3 on 2023-11-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0054_alter_blog_content_blog_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_content',
            name='Blog_ALT_TAG',
            field=models.CharField(blank=True, default='Blog ALT TAG', help_text='***** Put ALT TAG for SEO perpouses *****', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Blog_Slug',
            field=models.CharField(blank=True, default='Blog-Slug', help_text='***** Put Blog Title and Replace it by ( - ) is Recomended *****', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='Blog_Title',
            field=models.CharField(blank=True, default='Blog Title', help_text='***** Add Blog Title Over Here *****', max_length=100, null=True, unique=True),
        ),
    ]
