# Generated by Django 4.2.3 on 2023-11-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0055_blog_content_blog_alt_tag_blog_content_blog_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_content',
            old_name='Blog_date',
            new_name='Blog_Date',
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Introduction_Paragraph_1',
            field=models.TextField(blank=True, default='Add Introduction Paragraph', help_text='***** Include Introduction Paragraph No. 1 *****', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Introduction_Paragraph_2',
            field=models.TextField(blank=True, default='Add Introduction Paragraph', help_text='***** Include Introduction Paragraph No. 2 *****', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Introduction_Paragraph_3',
            field=models.TextField(blank=True, default='Add Introduction Paragraph', help_text='***** Include Introduction Paragraph No. 3 *****', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Paragraph_1',
            field=models.TextField(blank=True, default='Add Paragraph', help_text='***** Include Paragraph No. 1 *****', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Paragraph_2',
            field=models.TextField(blank=True, default='Add Paragraph', help_text='***** Include Paragraph No. 1 *****', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Paragraph_3',
            field=models.TextField(blank=True, default='Add Paragraph', help_text='***** Include Paragraph No. 1 *****', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Some_Quotation',
            field=models.CharField(blank=True, default='Add Quotation', help_text='***** Include Your Quotation *****', max_length=150, null=True),
        ),
    ]
