# Generated by Django 4.2.3 on 2023-11-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0056_rename_blog_date_blog_content_blog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='Introduction_Paragraph_1',
            field=models.TextField(blank=True, default='Add Introduction Paragraph 1', help_text='***** Include Introduction Paragraph No. 1 *****', null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='Introduction_Paragraph_2',
            field=models.TextField(blank=True, default='Add Introduction Paragraph 2', help_text='***** Include Introduction Paragraph No. 2 *****', null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='Introduction_Paragraph_3',
            field=models.TextField(blank=True, default='Add Introduction Paragraph 3', help_text='***** Include Introduction Paragraph No. 3 *****', null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='Paragraph_1',
            field=models.TextField(blank=True, default='Add Paragraph 1', help_text='***** Include Paragraph No. 1 *****', null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='Paragraph_2',
            field=models.TextField(blank=True, default='Add Paragraph 2', help_text='***** Include Paragraph No. 2 *****', null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='Paragraph_3',
            field=models.TextField(blank=True, default='Add Paragraph 3', help_text='***** Include Paragraph No. 3 *****', null=True),
        ),
    ]
