# Generated by Django 4.2.3 on 2023-11-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0057_alter_blog_content_introduction_paragraph_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_content',
            name='Headline_1',
            field=models.CharField(blank=True, default='Add Your HeadLine 1', help_text='***** Include HeadLine 1 *****', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Headline_1_Paragraph_1',
            field=models.TextField(blank=True, default='Add HeadLine 1 Paragraph 1', help_text='***** Include HeadLine 1 Paragraph No. 1 *****', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Headline_1_Paragraph_2',
            field=models.TextField(blank=True, default='Add HeadLine 1 Paragraph 2', help_text='***** Include HeadLine 1 Paragraph No. 2 *****', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Headline_1_Paragraph_3',
            field=models.TextField(blank=True, default='Add HeadLine 1 Paragraph 3', help_text='***** Include HeadLine 1 Paragraph No. 3 *****', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Headline_2',
            field=models.CharField(blank=True, default='Add Your HeadLine 2', help_text='***** Include HeadLine 2 *****', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Headline_2_Paragraph_1',
            field=models.TextField(blank=True, default='Add HeadLine 2 Paragraph 1', help_text='***** Include HeadLine 2 Paragraph No. 1 *****', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Headline_2_Paragraph_2',
            field=models.TextField(blank=True, default='Add HeadLine 2 Paragraph 2', help_text='***** Include HeadLine 2 Paragraph No. 2 *****', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Headline_2_Paragraph_3',
            field=models.TextField(blank=True, default='Add HeadLine 2 Paragraph 3', help_text='***** Include HeadLine 2 Paragraph No. 3 *****', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Headline_3',
            field=models.CharField(blank=True, default='Add Your HeadLine 3', help_text='***** Include HeadLine 3 *****', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Headline_3_Paragraph_1',
            field=models.TextField(blank=True, default='Add HeadLine 3 Paragraph 1', help_text='***** Include HeadLine 3 Paragraph No. 1 *****', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Headline_3_Paragraph_2',
            field=models.TextField(blank=True, default='Add HeadLine 3 Paragraph 2', help_text='***** Include HeadLine 3 Paragraph No. 2 *****', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Headline_3_Paragraph_3',
            field=models.TextField(blank=True, default='Add HeadLine 3 Paragraph 3', help_text='***** Include HeadLine 3 Paragraph No. 3 *****', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Image_for_HeadLine_1',
            field=models.ImageField(blank=True, help_text='***** Include Image for HeadLine 1 *****', null=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Image_for_HeadLine_1_ALT_TAG',
            field=models.CharField(blank=True, default='Add Image ALT TAG', help_text='***** Include ALT TAG for that Image *****', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Image_for_HeadLine_2',
            field=models.ImageField(blank=True, help_text='***** Include Image for HeadLine 2 *****', null=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Image_for_HeadLine_2_ALT_TAG',
            field=models.CharField(blank=True, default='Add Image ALT TAG', help_text='***** Include ALT TAG for that Image *****', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Image_for_HeadLine_3',
            field=models.ImageField(blank=True, help_text='***** Include Image for HeadLine 3 *****', null=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='Image_for_HeadLine_3_ALT_TAG',
            field=models.CharField(blank=True, default='Add Image ALT TAG', help_text='***** Include ALT TAG for that Image *****', max_length=100, null=True),
        ),
    ]
