# Generated by Django 4.2.3 on 2023-11-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0059_blog_content_author_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_content',
            old_name='Blog_Author',
            new_name='Blog_Author_Name',
        ),
    ]
