# Generated by Django 4.2.3 on 2023-11-22 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myService', '0060_rename_blog_author_blog_content_blog_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_content',
            old_name='Blog_Date',
            new_name='Blog_Post_Date',
        ),
    ]
